#lang racket
;; Júlio César Oliveira Rios
(require "conjuntos.rkt")

CONJUNTO-VAZIO
(membro-p-n? 3 '(1 2 3 4 5))

(printf "1:\n")
(conjunto-vazio? CONJUNTO-VAZIO)
(conjunto-vazio? 14)
(conjunto-vazio? '(q 1 "s" manoel))
(conjunto-vazio? 'q)
(conjunto-vazio? '(q (a d s) 22))
(printf "\n")

(printf "2:\n")
(conjunto? '(a b c a e))
(conjunto? '(a b c d e))
(conjunto? '(a b (c) "d" (e f)))
(conjunto? '(q 1 "s" manoel))
(conjunto? 'q)
(conjunto? '(q (a d s) 22))
(printf "\n")

(printf "3:\n")
(cardinalidade-c '(a b (c) "d" (e f)))
(cardinalidade-c '(a b (c) "d" ((e) f)))
(cardinalidade-c '(a b (c "") "d" ((e) f)))
(cardinalidade-c '(a b (c "") () "d" ((e) f)))
(cardinalidade-c '(a b (c "") (a s) "d" ((e) f)))
(printf "\n")

(printf "4:\n")
(iguais-c? '(a b c d e) '(e c a d b))
(iguais-c? '(a b c d e a) '((e) c a d b a))
(iguais-c? '(a a a a a) '(a a a a a))
(iguais-c? '(a) '(a a a a a))
(iguais-c? '("a") '(a))
(printf "\n")

(printf "5:\n")
(intersecta? '(a b c d e) '(e c z d w))
(intersecta? '(a b c (d) e) '(e c z d w))
(intersecta? '(()) '((a)))
(intersecta? '((a)) '((a)))
(intersecta? '((a)) '((a a (s))))
(intersecta? '((a a (s))) '((a a (s))))
(printf "\n")

(printf "6:\n")
(intersecao '(a b c d e) '(e c z d w))
(printf "\n")

(printf "7:\n")
(uniao '(a b c d e) '(e c z d w))
(uniao '(a b c d e) '((())))
(uniao '(a b c d e) '(e c z d (a) w))
(uniao '(ae) '(ae))
(uniao '((())) '((())))
(printf "\n")

(printf "8:\n")
(dif-conj '(a b c d e) '(e c z d w))
(dif-conj '(a b c d e) '(e a b c z d w))
(dif-conj '(a b) '(e c () d w))
(dif-conj '(a b ((()))) '((())))
(dif-conj '(a b ((()))) '(()))
(printf "\n")

(printf "9:\n")
(dif-sim '(a b c d e) '(e c z d w))
(dif-sim '(a b c d ()) '(e c z d w))
(dif-sim '(a b c d ()) '(e c z d (w)))
(dif-sim '(((()))) '(((a))))
(dif-sim '(a(a(a()))) '(a(a(a))))
(printf "\n")

(printf "10:\n")
(intersecao-lc)
(intersecao-lc '(a b c d e))
(intersecao-lc '(a b c d e) '(e c z d w))
(intersecao-lc '(a b c d e) '(e c z d w) '(w a m e z))
(intersecao-lc '(a b c d e) '(e c z d w) '(w a m z))
(intersecao-lc '(a b c d e) '(e c z d w) '(w a m e z) '((e)))
(printf "\n")

(printf "11:\n")
(uniao-lc)
(uniao-lc '(a b c d e))
(uniao-lc '(a b c d e) '(e c z d w))
(uniao-lc '(a b c d e) '(e c z d w) '(w a m e z))
(uniao-lc '(a b c d e) '(e c z d w) '(w a m z))
(uniao-lc '(a b c d e) '(e c z d w) '(w a m e z) '((e)))
(printf "\n")

(printf "12:\n >:(\n")
(printf "13:\n >:[")
(printf "\n")

